@extends('layouts.dashboard')
@section('title', 'POS')
@section('content')
@include('partials.page-header', ['title' => 'Point of Sale', 'subtitle' => 'Tap products to sell'])
@if($products->isEmpty())
<div class="text-center py-16 bg-white rounded-xl border text-slate-400">No products in stock. <a href="{{ route('products.create') }}" class="text-violet-600">Add products</a></div>
@else
<div class="grid lg:grid-cols-3 gap-6">
<div class="lg:col-span-2"><input id="search" placeholder="Search..." class="w-full mb-3 rounded-lg border-slate-300"><div class="grid sm:grid-cols-2 gap-3 max-h-[65vh] overflow-y-auto">@foreach($products as $product)<button type="button" class="product-card text-left bg-white border rounded-xl p-4 hover:border-violet-500" data-id="{{ $product->id }}" data-name="{{ $product->name }}" data-price="{{ $product->price }}" data-stock="{{ $product->stock }}"><div class="font-medium">{{ $product->name }}</div><div class="flex justify-between mt-2 text-sm"><span class="text-violet-600 font-semibold">{{ number_format($product->price,2) }}</span><span class="text-slate-400">Stock: {{ $product->stock }}</span></div></button>@endforeach</div></div>
<div class="bg-white border rounded-xl p-4 flex flex-col min-h-[400px] shadow-sm"><h3 class="font-semibold mb-3">Cart</h3><div id="cart-empty" class="flex-1 flex items-center justify-center text-slate-400 text-sm">Empty</div><ul id="cart-items" class="flex-1 space-y-2 hidden"></ul><div id="cart-footer" class="border-t pt-4 mt-4 hidden"><div class="flex justify-between text-lg font-bold mb-4"><span>Total</span><span id="cart-total">0.00</span></div><form method="POST" action="{{ route('pos.checkout') }}">@csrf<div id="checkout-fields"></div><input type="hidden" name="paid_amount" id="paid-amount"><button class="w-full py-3 bg-violet-600 text-white rounded-lg font-medium">Complete sale</button></form></div></div>
</div>
@push('scripts')<script>(()=>{const cart=new Map();const render=()=>{const items=document.getElementById('cart-items'),empty=document.getElementById('cart-empty'),footer=document.getElementById('cart-footer'),fields=document.getElementById('checkout-fields'),totalEl=document.getElementById('cart-total'),paid=document.getElementById('paid-amount');if(cart.size===0){items.classList.add('hidden');empty.classList.remove('hidden');footer.classList.add('hidden');fields.innerHTML='';return;}empty.classList.add('hidden');items.classList.remove('hidden');footer.classList.remove('hidden');let total=0,i=0;items.innerHTML='';fields.innerHTML='';cart.forEach(item=>{const sub=item.price*item.qty;total+=sub;items.innerHTML+=`<li class="flex justify-between bg-slate-50 rounded p-2 text-sm"><span>${item.name} x${item.qty}</span><span>${sub.toFixed(2)}</span></li>`;fields.innerHTML+=`<input type="hidden" name="items[${i}][product_id]" value="${item.id}"><input type="hidden" name="items[${i}][quantity]" value="${item.qty}">`;i++;});totalEl.textContent=total.toFixed(2);paid.value=total.toFixed(2);};document.querySelectorAll('.product-card').forEach(btn=>btn.onclick=()=>{const id=btn.dataset.id,stock=+btn.dataset.stock,qty=(cart.get(id)?.qty||0)+1;if(qty>stock)return alert('Not enough stock');cart.set(id,{id,name:btn.dataset.name,price:+btn.dataset.price,qty});render();});document.getElementById('search')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('.product-card').forEach(el=>el.classList.toggle('hidden',q&&!el.dataset.name.toLowerCase().includes(q)));});})();</script>@endpush
@endif
@endsection
